apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mizan23/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://admin:password@postgres-service:5432/mydb